Repository iotempire/iotempower, pull requests merged in 2024-05, with the labels that each got.

#111 Enabling GitHub Fancy Stuff
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE/default.md
  .github/PULL_REQUEST_TEMPLATE/documentation.md
  .github/PULL_REQUEST_TEMPLATE/feature_request.md
  .github/README.rst
  .github/SECURITY.md
  .github/SUPPORT.md
  .github/labels.yml
  README.rst
  doc/conf.py
  doc/examples_help/examples.rst
  doc/index-doc.rst
  doc/node_help/commands.rst
  doc/node_help/sgp30.rst
  doc/tool-support.rst
Labels: enhancement, help wanted, urgent

#112 fix bug contrib guide, update support.rst
  .github/CONTRIBUTING.md
  .github/README.rst
  .github/SUPPORT.md
  doc/first-node.rst
  doc/index-pi.rst
  doc/support.rst
Labels: bug, urgent

#118 SCD4X & fixes
  .github/README.rst
  doc/images/IoTempower_Readme_splash.png
  doc/images/IoTempower_Readme_splash2.png
  doc/index-pi.rst
  doc/node_help/analog.rst
  doc/node_help/commands.rst
  doc/node_help/ens16x.rst
  doc/node_help/scd4x.rst
  doc/node_help/sgp30.rst
  lib/node_types/esp/src/dev_ens16x.cpp
  lib/node_types/esp/src/dev_ens16x.h
  lib/node_types/esp/src/dev_scd4x.cpp
  lib/node_types/esp/src/dev_scd4x.h
  lib/node_types/esp/src/dev_sgp30.cpp
  lib/node_types/esp/src/dev_sgp30.h
  lib/node_types/esp/src/devices.ini
Labels: bug, enhancement

#116 add linux laptop install docs
  doc/installation.rst
  doc/manjaro-gateways-setup.rst
Labels: enhancement

#126 Update labels.yml: add documentation label, color and description
  .github/labels.yml
Labels: enhancement
